name: Deploy to GitHub Pages

on:
  push:
    branches:
      - v1  # Trigger on push to the 'v1' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allow write access to repository contents (required for pushing changes)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4
        with:
          submodules: false  # Disable submodules to avoid errors

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # Action to deploy to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the default token
          publish_dir: ./  # Publish from the root directory, where your 'index.html' is located
          publish_branch: gh-pages  # Push to the 'gh-pages' branch
